name: Recovering secrets
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Qual ambiente quer recuperar o env?
jobs:
  help:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Recupera o ambiente
        shell: bash
        run: |
          echo "Gerando hash do env para ser descriptografado"
          echo "$(echo """${{ toJSON(secrets) }}""" | openssl enc -e -aes-256-cbc -a -pbkdf2 -md md5 -iter '${{ secrets.OPENSSL_ITER }}' -k '${{ secrets.OPENSSL_PASSWORD }}')" > artifact
          echo "Com o hash acima gerado, baixe o artefato gerado e rode o seguinte comando em seu terminal:"
          echo "echo PASTE_HERE | openssl base64 -d | openssl enc -d -pbkdf2 -iter -md md5 numeroIteracoes -aes-256-cbc -k senha > env.json"
      - name: Upload artefato
        uses: actions/upload-artifact@v3
        with:
          name: hash-ambiente
          path: artifact
