- envFrom:
  - secretRef:
      name: backend-teste
  image: 607751015014.dkr.ecr.sa-east-1.amazonaws.com/proesc-backend:app-main-a8306e85b63675ff2a6be56910c3c958353bb43d
  imagePullPolicy: IfNotPresent
  name: main-app
  resources:
    requests:
      cpu: 100m
      memory: 248Mi
- image: 607751015014.dkr.ecr.sa-east-1.amazonaws.com/proesc-backend:web-main-a8306e85b63675ff2a6be56910c3c958353bb43d
  imagePullPolicy: IfNotPresent
  name: main-web
  ports:
  - containerPort: 8080
    name: http
    protocol: TCP
  readinessProbe:
    httpGet:
      path: /
      port: 8080
  resources:
    requests:
      cpu: 100m
      memory: 248Mi
